### ISSUE TITLE
Team Scrum Report 1 (May 29th)

### ISSUE THREAD

**Issue by tillson27** [CPSC-455-Summer-2022/WixHub_Project_S22#1]

**Comment by tillson27** [comment]
### Josh Tillson - i4i2b

**1) What did you work on this past iteration (2 weeks)?**
- Project ideation (an extended process where we pushed to come up with a series of project ideas, evaluate them based on an agreed-upon selection criteria and then solidifying our top selection)
- Defining the scope of the project and capturing the project description in the readme
- Researching similarly scoped projects and their associated stack/development requirements
- Creation of preliminary requirements (minimal, standard, stretch) and the engineering tasks for the minimum requirements 

**2)  What were any major issues/challenges you ran into?**
- Coordinating time to meet as a group (I unfortunately was dealing with covid at the time and couldn't meet up in person)
- Deciding on a project topic is always difficult especially as many of our more unique and creative ideas would have required a lot of additional work outside the scope of the course's material.

**3) What do you plan to work on for this coming iteration (2 weeks)?**
- Set-up/establish our teams project management process/system using GitHub (Projects and Issues)
- Contribute to one of the front end react pages required - likely welcome page (Carousel introduction/walkthrough)
- Begin setting up our database and associated connections (MongoDB)

**Comment by ronincunningham** [comment]
### Ronin Cunningham - m0c2b

**1) What did you work on this past iteration (2 weeks)?**
- UML diagram of the major components of our website
- Assigning tasks to each group member with appropriate deadlines

**2)  What were any major issues/challenges you ran into?**
- Figuring out an idea that matched the marking rubric and was within the scope of the course

**3) What do you plan to work on for this coming iteration (2 weeks)?**
- Finish one of our mock-up pages in React
- Communicate with fellow teammates regarding shared data between the frontend and the database

**Comment by zkwvcin** [comment]
### Weichong Zhao - x4x2b
**1) What did you work on this past iteration (2 weeks)?**
- Project ideation (an extended process where we pushed to come up with a series of project ideas, evaluate them based on an agreed-upon selection criteria and then solidifying our top selection)
- Researching similarly scoped projects and their associated stack/development requirements

**2)  What were any major issues/challenges you ran into?**

- Adjusting our project to meet the criteria and time complexity of the course

**3) What do you plan to work on for this coming iteration (2 weeks)?**
- Set-up/establish our teams project management process/system using GitHub (Projects and Issues)
- Set-up our teams time stamp
- Contribute to the work we're being assigned on

**Comment by lzwsl** [comment]
Sherman Lam - z2o2b
1) What did you work on this past iteration (2 weeks)?

- Project ideation (an extended process where we pushed to come up with a series of project ideas, evaluate them based on an agreed-upon selection criteria and then solidifying our top selection)
- Creating mockups of our potential UI
- Researching other projects and determining stack/development requirements

2) What were any major issues/challenges you ran into?

- Coordinating time to meet as a group
- Manipulating our ideas to fit with and align with the project requirements

3) What do you plan to work on for this coming iteration (2 weeks)?

- Set-up/establish our teams project management process/system using GitHub (Projects and Issues)
- Create refined mock up for the main pages of our site
- Figure out what data needs to be stored in the database and how the backend might interact with the front end
