### ISSUE TITLE
Team Scrum Report (June 12)

### ISSUE THREAD

**Issue by lzwsl** [CPSC-455-Summer-2022/WixHub_Project_S22#22]
Updates for this sprint

**Comment by lzwsl** [comment]
### **Sherman Lam**
**1) What did you work on this past iteration (2 weeks)?**

Created FIGMA design mockups for the website as well as determine what kind of features our site may feature
Determine components that may be needed for our site to function well as well as ensure that any features would be accounted for
Create User Dashboard component and have it display on our site

**2) What were any major issues/challenges you ran into?**

Deciding how the page would be laid out as well as figuring what features are viable in the timespan that we are working with
Initial uploads to github and having various people upload their implementations caused some small issues regarding the ability to build the dev branch

**3) What do you plan to work on for this coming iteration (2 weeks)?**

I plan on revamping/revising the figma mockup of our website and then tranfering those designs into our frontend code
Create more components that we may need, as well as revising existing components to comply with our figma design

**Comment by ronincunningham** [comment]
1) What did you work on this past iteration (2 weeks)?

Created components for the different pages of our site. 
Created nav bar component with react-router to route the components.

2) What were any major issues/challenges you ran into?

Someone installed npm packages in the wrong folder which caused our app to crash.
Figuring out this weird bug with react-router's npm install (got it working now though)

3) What do you plan to work on for this coming iteration (2 weeks)?

Flesh out front end React components to further develop our website.
Integrate material UI into our page's components.

**Comment by tillson27** [comment]
### Josh Tillson - i4i2b

**1) What did you work on this past iteration (2 weeks)?**
- Establishing the list of destinations, associated questions and logical mapping of question answers to destination recommendation (to prepare backend recommendation generator structure). Currently this was done in Excel but will be transferred to Node.
- Created the displayed recommendation component on the User Dashboard shown upon going through the series of questions. 
- Mapped out the required components needed for the web application and assigned responsibility using GitHub issues. 

**2)  What were any major issues/challenges you ran into?**
- Team member miscommunication when it came to installing packages and dependencies in the correct directory. 
- Finding time to dedicate to the project between the assignment and a extended responsibilities at work. 

**3) What do you plan to work on for this coming iteration (2 weeks)?**
- Establish Express backend and start to actually build out the recommendation generator that I mapped out in the previous sprint. 
- Improve the styling of my existing components on the User Dashboard and the user interface for the questionnaire. 
- Work with Kevin to begin connecting Express to the setup MongoDB.

**Comment by zkwvcin** [comment]
Weichong Zhao
1) What did you work on this past iteration (2 weeks)?

Created Sign-up page component
Created LoginVsSignup component



2) What were any major issues/challenges you ran into?

npm doesn’t  work

3) What do you plan to work on for this coming iteration (2 weeks)?

Mongo DB
