### ISSUE TITLE
Team Scrum Report (June 26)

### ISSUE THREAD

**Issue by lzwsl** [CPSC-455-Summer-2022/WixHub_Project_S22#32]
Reports for the June 26 week

**Comment by lzwsl** [comment]
### Sherman Lam

**1) What did you work on this past iteration (2 weeks)?**

- Finished Figma Mock-up, created the basic guidelines for user dashboard, login, recommendations
- Determine components that may be needed for our site to function well as well as ensure that any features would be accounted for
- revamp the navigation bar and work on converting our logo into a SVG file (in progress)

**2) What were any major issues/challenges you ran into?**

- Deciding how the page would be laid out as well as figuring what kind of information we would need to collect from use user and how we process that and send it to the backend
- branching issues and commuting to the correct branch, we also had issues with conflicts and merging files

**3) What do you plan to work on for this coming iteration (2/3 weeks)?**

- Create more components that we may need, as well as revising existing components to comply with our figma design
- Looking into and creating the login authentication system for our site and figuring out how we store user login information in the MongoDB database

**Comment by zkwvcin** [comment]
Sherman Lam
1) What did you work on this past iteration (2 weeks)?
Working on Database model setup
Discuss with teammates on collections that we need

2) What were any major issues/challenges you ran into?
Unfamiliar with MongoDB

3) What do you plan to work on for this coming iteration (2/3 weeks)?
Complete our database model
Connect it to the server

**Comment by tillson27** [comment]
### Josh Tillson - i4i2b

**1) What did you work on this past iteration (2 weeks)?**
- Created server/backend API using Express and node.js 
- Created three major routes (questions, destinations and users)
- Created mock data for each of the routes, formatted for as a json object with design considerations for mongoDB storage
- Created multiple endpoints for each route
- Created the redux infrastructure using thunks to set up all the required methods to call each of the backend apis endpoints 
- Created 11 redux actions
- Added front end error handling for the connected API calls
- Created recommendation generator function to assign users a destination recommendation based on their responses to a series of 8 multiple choice questions

**2)  What were any major issues/challenges you ran into?**
- Team member miscommunication and priority setting

**3) What do you plan to work on for this coming iteration (2 weeks)?**
- Add server-side error handling and the appropriate status codes
- Build upon the existing recommendation generator function to add greater depth and functionality (i.e. ML applications)
- Support team members as they aim to connect MongoDB to the server
