### ISSUE TITLE
Team Scrum Report (July 17)

### ISSUE THREAD

**Issue by lzwsl** [CPSC-455-Summer-2022/WixHub_Project_S22#40]
Scrum report for July 17

**Comment by lzwsl** [comment]
### Sherman Lam

**1) What did you work on this past iteration (2 weeks)?**

Worked on user login, user logged in persistence
Worked on user authentication with mongodb

**2) What were any major issues/challenges you ran into?**

Determining how users could be authenticated
Getting DB access correctly

**3) What do you plan to work on for this coming iteration (2/3 weeks)?**

Finalize user login methods as well as determine optimal user state

**Comment by tillson27** [comment]
### Josh Tillson - i4i2b

**1) What did you work on this past iteration (2 weeks)?**
- Cleaned up and debugged endpoints
- Added greater complexity to the recommendation generator endpoint
- Researched ML options for adding logic to the recommendation generator 
- Began to explore different ways to leverage NLP in the recommendation generator and created a library of data to leverage for each destination using a wikipedia web scraper.

**2)  What were any major issues/challenges you ran into?**
- This week was pretty good, I would say the biggest challenge is priority setting as we look towards pulling this project together and presenting something both functional and viable.
- Team mobilization (communicating and getting together to make headway on the project)

**3) What do you plan to work on for this coming iteration (2 weeks)?**
- Continue adding server-side error handling and the appropriate status codes
- Continue building upon the existing recommendation generator function to add greater depth and functionality (i.e. ML applications)
- Continue supporting team members as they aim to connect MongoDB to the server

**Comment by zkwvcin** [comment]
Weichong Zhao -x4x2b

1) What did you work on this past iteration (2 weeks)?

Set up MongoDB API with associates endpoint.

2) What were any major issues/challenges you ran into?

Setting up the route and paths.

3) What do you plan to work on for this coming iteration (2/3 weeks)?

Complete database setup for image storing and edit recommendations system with database

**Comment by ronincunningham** [comment]
Ronin Cunningham - m0c2b

1. What did you work on this past iteration (2 weeks)?
Hooking the frontend to the backend apis
2. What were any major issues/challenges you ran into?
Trying to mock a user since I was waiting on another teammate to get the login working
3. What do you plan to work on for this coming iteration (2/3 weeks)?
Finish other components not related to Signup and Login (ie user dashboard and landing page)
