### ISSUE TITLE
Team Scrum Report (July 31)

### ISSUE THREAD

**Issue by lzwsl** [CPSC-455-Summer-2022/WixHub_Project_S22#51]
Team Reports

**Comment by lzwsl** [comment]
### Sherman Lam
**1) What did you work on this past iteration (2 weeks)?**

Worked on user login, user logged in persistence
Worked on user authentication with mongodb
Worked on updating Navbar to refllect changes
Worked on having protected routing for logged-in/out and redirecting

**2) What were any major issues/challenges you ran into?**

Determining how users could be authenticated
getting the routing done
getting the authentication to work

**3) What do you plan to work on for this coming iteration (2/3 weeks)?**

Finalize user login methods as well as determine optimal user state
finalize account creation as well as work on some other front end components
fix error handling as well as redircting the routes

**Comment by ronincunningham** [comment]
Ronin Cunningham - m0c2b

1. What did you work on this past iteration (2 weeks)?
Revamping the Home Page, Connecting endpoints to User Dashboard, conditionally rendering components depending on if user is logged in or not
3. What were any major issues/challenges you ran into?
Calling async function in useEffect hook caused it to update twice/have race conditions, but I fixed it with a boolean flag pattern. Also coordinating with my teammate for the logging in may get confusing when we try to combine our changes.
4. What do you plan to work on for this coming iteration (2 weeks)?
Revamp the User Dashboard, Make the Account/Settings page. Help teammate with question and answer flow

**Comment by tillson27** [comment]
### Josh Tillson - i4i2b

**1) What did you work on this past iteration (2 weeks)?**
- Cleaned up and debugged endpoints, connecting endpoints to DB
- Added greater complexity to the recommendation generator endpoint
- Deployed backend and frontend to Heroku
- Added SwaggerUI documentation for all of our endpoints

**2)  What were any major issues/challenges you ran into?**
- This week was pretty good, I would say the biggest challenge is priority setting as we look towards pulling this project together and presenting something both functional and viable.
- Team mobilization (communicating and getting together to make headway on the project)

**3) What do you plan to work on for this coming iteration (2 weeks)?**
- Continue adding server-side error handling and the appropriate status codes
- Continue building upon the existing recommendation generator function to add greater depth and functionality (i.e. ML applications)
- Support team members using api endpoints for frontend components

**Comment by zkwvcin** [comment]
Weichong Zhao -x4x2b

1) What did you work on this past iteration (2 weeks)?

Modify MongoDB end points
working on persistence for data storing to DB

2) What were any major issues/challenges you ran into?

Connecting with frontends with proper methods 

3) What do you plan to work on for this coming iteration (2/3 weeks)?

Finalize our DB
